output_root: '../workspaces/stego'
pytorch_data_dir: '/workspaces/stego/datasets'
experiment_name: "cityscapes"
res: 224
batch_size: 2
num_workers: 2
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "/workspaces/stego/saved_models/cityscapes_vit_base_1.ckpt"
  - "/workspaces/stego/checkpoints_old/cityscapes/cityscapes_cityscapes_date_Sep25_12-45-50_dinov2_vit16/epoch=5-step=3600.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
